### ISSUE TITLE
Final Formatting Master Issue

### ISSUE THREAD

**Issue by dipshit** [edegens/ptype#88]
If there is a linked issue for a task please read it.

- [x] Number formatting. Currently 2 sections are labelled the 6th section. (@dipshit)
- [x] #85 Replace (package, platform) -> library. (@JackyChiu )
- [x] #85 developers -> users (@bkzhang )
- [x] Verify numbers of all figures & tables and link them in the preface #66 (@dipshit )
- [x] Verify all text follows the formatting guide of #69  (unassigned)
- [x] Regen table of contents (@dipshit)
- [x] distributed memory -> distributed storage (@JackyChiu )
